### ISSUE TITLE
[dev.icinga.com #12870] Wrong path when using "check_by_ssh" commands

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-graphite#10] opened 2016-10-07 09:17 UTC
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12870

**Created by twidhalm on 2016-10-07 09:17:15 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-07 09:17:15 +00:00 (in Redmine)_

---

Hi,

While this might be similar to [\#11572](https://dev.icinga.com/issues/11572) I don't want to take chances, so I opened this issue. When checking services via SSH by using the `by_ssh` command from the ITL, the path to the metrics in the graphite tree is different from services that are checked directly. I can't imagine a universal fix for this which works for "custom built" commands as well but at least the checkcommands from the ITL could be supported by the graphite module.

Cheers,
Thomas

**Comment by Al2Klimov** [comment] 2017-09-22 13:54
Closing as duplicate of #5. /cc @widhalmt

**Closed by Al2Klimov** 2017-09-22 13:54 UTC
Labels: bug
