### ISSUE TITLE
SQL Collation error

### ISSUE THREAD

**Issue by ChaotY2k** [Icinga/icingaweb2-module-graphite#117] opened 2018-01-09 12:26 UTC
SQL-Error in icingaweb2:

SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8', query was: SELECT ho.name1 AS host_name, h.display_name COLLATE latin1_general_ci AS host_display_name, hs.check_command AS host_check_command, hcv_check_command.varvalue AS _host_check_command FROM icinga_hosts AS h
 INNER JOIN icinga_objects AS ho ON ho.object_id = h.host_object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
 INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
 LEFT JOIN icinga_customvariablestatus AS hcv_check_command ON h.host_object_id = hcv_check_command.object_id AND hcv_check_command.varname = 'check_command' COLLATE latin1_general_ci ORDER BY h.display_name COLLATE latin1_general_ci ASC LIMIT 25

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(744): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /usr/share/php/Icinga/Data/Db/DbConnection.php(278): Zend_Db_Adapter_Abstract->fetchRow(Object(Zend_Db_Select))
#5 /usr/share/php/Icinga/Data/SimpleQuery.php(577): Icinga\Data\Db\DbConnection->fetchRow(Object(Icinga\Module\Monitoring\Backend\Ido\Query\HoststatusQuery))
#6 /usr/share/php/Icinga/Data/SimpleQuery.php(453): Icinga\Data\SimpleQuery->fetchRow()
#7 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(539): Icinga\Data\SimpleQuery->hasResult()
#8 /usr/share/icingaweb2/modules/graphite/application/views/scripts/list/hosts.phtml(25): Icinga\Module\Monitoring\DataView\DataView->hasResult()
#9 /usr/share/php/Icinga/Web/View.php(233): include('/usr/share/icin...')
#10 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render('list/hosts.phtm...')
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('list/hosts.phtm...', NULL)
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#16 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('hostsAction')
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#20 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#21 {main}

## Your Environment

* Module version (System - About): 0.9.0
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: ubuntu
* Webserver, PHP versions: PHP 5.6.32-1+ubuntu16.04.1+deb.sury.org+2

**Comment by Al2Klimov** [comment] 2018-01-10 17:22
Hello @ChaotY2k and thank you for reporting!

This seems to be an Icinga Web 2 error. Please could you try w/ the latest version?

Best,
AK

**Comment by bobapple** [comment] 2018-01-19 11:56
I'm closing this issue since it's not a bug in this module.
@ChaotY2k please open an issue at the icingaweb2 project

**Closed by bobapple** 2018-01-19 11:56 UTC
Labels: invalid

**Comment by Alives** [comment] 2018-05-26 07:59
I'm seeing this error as well on a fresh install on Xenial.

icinga2=2.8.4-1.xenial
icingaweb2=2.5.3-1.xenial
graphite module=1.0.1
apache2=2.4.18-2ubuntu3.8
php=7.0.30-0ubuntu0.16.04.1

**Comment by Farfaday** [comment] 2018-05-28 12:47
Same for me !

```
SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8mb4', query was: SELECT ho.name1 AS host_name, h.display_name COLLATE latin1_general_ci AS host_display_name, hs.check_command AS host_check_command, hcv_check_command.varvalue AS _host_check_command FROM icinga_objects AS ho
INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
LEFT JOIN icinga_customvariablestatus AS hcv_check_command ON h.host_object_id = hcv_check_command.object_id AND hcv_check_command.varname = 'check_command' COLLATE latin1_general_ci ORDER BY h.display_name COLLATE latin1_general_ci ASC LIMIT 25
```
No issue with the rest of icingaweb2 :)

**Comment by lippserd** [comment] 2018-05-29 07:27
https://github.com/Icinga/icingaweb2/issues/2508 fixes this issue. Either wait for Web 2 2.6.0 which will be released in roughly one month or switch to our snapshot packages for the moment.

**Comment by Alives** [comment] 2018-05-31 07:35
The snapshots don't seem to fix it... icingaweb2 2.5.3.2018.04.28+1.xenial-0 doesn't at least.

**Comment by PinkFrog** [comment] 2019-06-25 10:52
Hi, 
same issue here with the following environment: 

    Module version (System - About): 1.1.0
    Icinga Web 2 version and modules (System - About): 2.6.3
    Icinga 2 version (icinga2 --version): r2.10.5-1
    Operating System and version: Debian 9
    Webserver, PHP versions: Apache/2.4.25 (Debian), PHP 7.0.33-0+deb9u3

Best, 
PinkFrog

**Comment by Goldenflamer** [comment] 2019-08-24 13:03
Same issue here

**Comment by Goldenflamer** [comment] 2019-08-24 13:44
I fixed the issue!! @PinkFrog 

Edit the following file:
nano /etc/icingaweb2/resources.ini

For each database connection add the following line:

charset = "latin1"

remove all other chartset= lines and voila everything is working fine.

**Comment by dnsmichi** [comment] 2019-08-27 08:07
Similar issue with the IDO resource is discussed in detail here: https://community.icinga.com/t/problem-with-umlauts-in-contacts/1958

**Comment by gabrielrota** [comment] 2020-08-31 08:01
I fixed my problem specifying the "Character Set" utf8mb4, as in database,  for my icinga_ido resource. Previously was empty.
