### ISSUE TITLE
Icinga2 graphite graph dissapear from Icinga when auto refresher enabled

### ISSUE THREAD

**Issue by samogoljat** [Icinga/icingaweb2-module-graphite#316] opened 2023-09-11 06:41 UTC
Icinga auto refresher makes integrated graphite graph dissapear after it refreshes. This happens when i change timeline from default to other custom time.

I confirmed this by disabling auto refresher, then the graph stayed and didn’t dissapear.
I also confirmed with changing auto refresher speed to slow, then it stayed longer, but dissapeared after longer time.
Interesting is that it dissapears only when timeline is changed from default, if left default it doesn’t dissapear.

I also tried different versions of graphite icinga module. From version 1.1.0 till latest 1.2.3.
Same problem.

![Untitled](https://github.com/Icinga/icingaweb2-module-graphite/assets/66040096/71e1c09c-3ed5-4db9-8235-a408bbc6d2ed)

Untitled
Untitled
1036×864 102 KB
Icinga Web 2 Version 2.11.4
icinga/icinga-php-thirdparty 0.11.0
icinga/icinga-php-library 0.12.0
Icinga version - 2.13.2-1
AlmaLinux release 8.8 (Sapphire Caracal)
graphite 1.2.3
PHP 8.0.30

**Comment by nilmerg** [comment] 2023-09-11 13:45
Duplicate of https://github.com/Icinga/icingaweb2/issues/4996

**Closed by nilmerg** 2023-09-11 13:45 UTC

**Comment by samogoljat** [comment] 2023-09-12 18:10
Thank you for information!
