### ISSUE TITLE
No performance graphs on Icingaweb2 with the graphite module

### ISSUE THREAD

**Issue by mjs2012** [Icinga/icingaweb2-module-graphite#309] opened 2023-07-13 22:17 UTC
## Current Behavior
![grafik](https://github.com/Icinga/icingaweb2-module-graphite/assets/3264365/93cb4590-511a-4e1a-83ac-56fad3c47cbe)

No graphs where shown in the Icinagweb2 graphite module.
Therfore is the following URL to be used:
```
http://XXX.XXX.XXX.XXX/icingaweb2/graphite/graph/host?host.name=icinga-test&host.check_command=hostalive&template=hostalive-rta&start=-3600&end=&width=350&height=200&legend=1&bgcolor=ffffff&fgcolor=535353&majorGridLineColor=c9c9c9&minorGridLineColor=ffffff&r=1689283706752
```

By using the URL in a new Tab, the following result is shown:
![grafik](https://github.com/Icinga/icingaweb2-module-graphite/assets/3264365/3fc824e8-f349-4893-b72f-93775c1269dd)

The connection works for me by Graphite-Web or Graphite-API. All Metris are available.

My result of the debugging was, that the color options are not working if any integers are included in the URL.
If I change some parameters manually in the URL, it works. See here:
```
http://XXX.XXX.XXX.XXX/icingaweb2/graphite/graph/host?host.name=icinga-test&host.check_command=hostalive&template=hostalive-rta&start=-3600&end=&width=350&height=200&legend=1&bgcolor=white&fgcolor=black&majorGridLineColor=blue&minorGridLineColor=blue&r=1689283916697
```
![grafik](https://github.com/Icinga/icingaweb2-module-graphite/assets/3264365/7149876c-4546-4523-9469-69dd590e4ebe)

The problems on my test systems are affected by using the standard dark theme and the icingalegacy theme theme.

## Possible Solution
The following parameters are effeced:
* bgcolor
* fgcolor
* minorGridLineColor
* majorGridLineColor

My workaround is, to use the following parameters in all my graphite templates by the urlparams section:
```
bgcolor = "white"
fgcolor = "black"
minorGridLineColor = "blue"
majorGridLineColor = "blue"
```
Here the result:
![grafik](https://github.com/Icinga/icingaweb2-module-graphite/assets/3264365/1d390d77-531b-4f1e-b719-166b473f719b)

Is it possible to modify the standard URL query in the code for using standard color keyword (like black, white, blue,...) ?
Is there any option to set a this standard parameters in the Icingaweb graphite module or the config.ini?
Do you have any other ideas without of changing all graphite templates?

## Your Environment
* Module version (System - About):
graphite 1.2.3
icingalegacytheme 1.0.0
incubator 0.20.0
ipl v0.5.0
monitoring 2.11.4
reactbundle 0.9.0
* Icinga Web 2 version and modules (System - About): 2.11.4
* Icinga 2 version (`icinga2 --version`): r2.14.0-1
* Graphite (carbon, web, whisper) version: 1.1.7-1
* Operating System and version: Ubuntu 22.04
* Webserver, PHP versions: 8.1

**Comment by nilmerg** [comment] 2023-07-17 08:17
The exact error from Graphite would be interesting. I remember an issue with a particular Graphite version, though your's seems to be fairly recent. :thinking:

**Comment by nilmerg** [comment] 2023-07-17 10:16
The apache log isn't that helpful. Isn't there a log by graphite itself?

**Comment by mjs2012** [comment] 2023-07-17 14:14
No, I use the Graphit-API  or the Graphite-Web. I use the Apache2 with the proxy modul for accessing Graphite.
The results are always the same.
By using Grafana with the Graphite plugin, I have no problems.

**Comment by mjs2012** [comment] 2023-07-28 14:20
Which log do you mean?
I have no other logs, because I use the Apache and Mod Proxy for Graphite-API and a Vhost config for Graphite-Web with port 8081 for accessing.
The access from Grafana works perfectly for me, but here are no color options in the render call/query included.

**Comment by nilmerg** [comment] 2024-03-11 09:03
I've found what I've remembered: #273

The problem is the version of `graphite-api` it seems, which matches with what has been reported there.

**Comment by nilmerg** [comment] 2024-03-11 09:03
Duplicate of #273

**Closed by nilmerg** 2024-03-11 09:03 UTC
Labels: needs-feedback
