### ISSUE TITLE
Graphs in Icinga disappear

### ISSUE THREAD

**Issue by BT-Khaled** [Icinga/icingaweb2-module-graphite#296] opened 2023-06-09 12:48 UTC
## Expected Behavior

Icinga graphs must always be visible.

![image](https://github.com/Icinga/icingaweb2-module-graphite/assets/135836432/c583af13-c5c8-4ef1-a933-a2cd8bc9e8db)

## Current Behavior

after using the filter for the graph it disappears after a few seconds.

![image](https://github.com/Icinga/icingaweb2-module-graphite/assets/135836432/3dc16ee9-1d34-4098-998b-421c8ee0d697)

## Possible Solution

To bring up the graphs again, the page can be reloaded.

## Steps to Reproduce (for bugs)

1. open a service/host.
2.  Change the scaling period of the graph.
3. wait for a few seconds.
4. the grapgs will be disappeared.

## Context

i want to check the history of the hosts/services.

## Your Environment

* Module version (System - About): graphite: 1.2.2
* Icinga Web 2 version and modules (System - About): 2.11.4
* Icinga 2 version (`icinga2 --version`): 2.13.7
* Graphite (carbon, web, whisper) version: 1.2.2
* Operating System and version: Red Hat Enterprise Linux Server 7.9
* Webserver, PHP versions: Webserver: Apache/2.4.6,  PHP: 8.1.19

**Comment by nilmerg** [comment] 2023-06-28 12:19
Duplicate of https://github.com/Icinga/icingaweb2/issues/4996

**Closed by nilmerg** 2023-06-28 12:19 UTC
