### ISSUE TITLE
Graphite list filter {} doesn't get included into graph

### ISSUE THREAD

**Issue by mkayontour** [Icinga/icingaweb2-module-graphite#221] opened 2019-09-11 16:46 UTC
When using the list filter from graphite, the found metric doesn't get include or merged into the graph.

```
[example.graph]
check_command = "passive"

[example.metrics_filters]
list.value = "$service_name_template$.perfdata.example_{listitem}.value"
warn.value  = "$service_name_template$.perfdata.warning.value"
crit.value  = "$service_name_template$.perfdata.critical.value"

[example.urlparams]
title = Example
areaAlpha = "0.5"
areaMode = "all"
lineWidth = "2"
min = "0"
yUnitSystem = "none"

[example.functions]
list.value = "alias(color($metric$, '#1a7dd7'), 'Time (sec)')"
warn.value = "alias(color($metric$, 'orange'), 'Warning (sec)')"
crit.value = "alias(color($metric$, 'red'), 'Critical (sec)')"
```

```
+ Icinga check command: 'passive'
+ Obscured check command: NULL
+ Applying templates for check command 'passive'
++ Applying template 'sakuli_suite'
+++ Fetched 1 metric(s) from 'http://localhost:8000/metrics/expand?query=icinga2.hostname.services.%2A.service.passive.perfdata.example_%7Blistitem%7D.value'
+++ Fetched 1 metric(s) from 'http://localhost:8000/metrics/expand?query=icinga2.hostname.services.%2A.service.passive.perfdata.warning.value'
+++ Fetched 1 metric(s) from 'http://localhost:8000/metrics/expand?query=icinga2.hostname.services.%2A.service.passive.perfdata.critical.value'
+++ Excluded 0 metric(s)
+++ Combined 2 metric(s) to 1 chart(s)
```

## Your Environment
* Module version (System - About): 1.1.0
* Icinga Web 2 version and modules (System - About): 2.7.1
* Icinga 2 version (`icinga2 --version`): 2.10.5_1
* Graphite (carbon, web, whisper) version: 1.1.5
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: 7.2.19-0ubuntu0.18.04.2

**Comment by sukhwinder33445** [comment] 2022-03-14 17:05
duplicate of #220

**Closed** 2022-03-14 17:05 UTC
Labels: area/templates
