### ISSUE TITLE
After update no graphs are displayed anymore

### ISSUE THREAD

**Issue by lbetz** [Icinga/icingaweb2-module-graphite#273] opened 2022-04-13 08:00 UTC
Just updating to from v1.1.0 to v1.2.0 on an icingaweb 2.9.6 (after updated to 2.10.0 the same) no graphs are displayed anymore.

The documentation shows that icinga-php-thirdparty >= 0.11.0 is needed, but the module says >= 0.10.0, last one is installed.

Icingaweb2 is installed as package from packages.icinga.com on a debian bullseye.

Graphs assembling process record:
+ Icinga check command: 'hostalive'
+ Obscured check command: NULL
+ Applying templates for check command 'hostalive'
++ Applying template 'hostalive-rta'
+++ Fetched 1 metric(s) from 'https://grafana.example.com:8542/metrics/expand?query=icinga2.carbon-de-hub-1_example.host.hostalive.perfdata.rta.value'
+++ Excluded 0 metric(s)
+++ Combined 1 metric(s) to 1 chart(s)
++ Applying template 'hostalive-pl'
+++ Fetched 1 metric(s) from 'https://grafana.exmple.com:8542/metrics/expand?query=icinga2.carbon-de-hub-1_example_com.host.hostalive.perfdata.pl.value'
+++ Excluded 0 metric(s)
+++ Combined 1 metric(s) to 1 chart(s)
+ Applying default templates, excluding previously used metrics
++ Applying template 'default-host'
+++ Fetched 2 metric(s) from 'https://grafana.examplel.com:8542/metrics/expand?query=icinga2.carbon-de-hub-1_example_com.host.hostalive.perfdata.%2A.value'
+++ Excluded 2 metric(s)
+++ Combined 0 metric(s) to 0 chart(s)
++ Not applying template 'default-service'
++ Applying template 'multi2-host'
+++ Fetched 0 metric(s) from 'https://grafana.example.com:8542/metrics/expand?query=icinga2.carbon-de-hub-1_example_com.host.hostalive.perfdata.%2A.%2A.value'
+++ Excluded 0 metric(s)
+++ Combined 0 metric(s) to 0 chart(s)
++ Not applying template 'multi2-service'
++ Applying template 'multi3-host'
+++ Fetched 0 metric(s) from 'https://grafana.example.com:8542/metrics/expand?query=icinga2.carbon-de-hub-1_example_com.host.hostalive.perfdata.%2A.%2A.%2A.value'
+++ Excluded 0 metric(s)
+++ Combined 0 metric(s) to 0 chart(s)
++ Not applying template 'multi3-service'

**Comment by nilmerg** [comment] 2022-04-13 08:39
Hi,

the only thing of note here are the literal `*`. Though, I tried the same now for the disk check and they work just fine. Please show the template(s) and the debug output of 1.1.0.

**Comment by lbetz** [comment] 2022-04-13 09:02
the default template is used, and hier the debug output from v1.1.0:

+ Icinga check command: 'hostalive'
+ Obscured check command: NULL
+ Applying templates for check command 'hostalive'
++ Applying template 'hostalive-rta'
+++ Fetched 1 metric(s) from 'https://grafana.example.com:8542/metrics/expand?query=icinga2.wd-de-hub-1_example.host.hostalive.perfdata.rta.value'
+++ Excluded 0 metric(s)
+++ Combined 1 metric(s) to 1 chart(s)
++ Applying template 'hostalive-pl'
+++ Fetched 1 metric(s) from 'https://grafana.example.com:8542/metrics/expand?query=icinga2.wd-de-hub-1_example_com.host.hostalive.perfdata.pl.value'
+++ Excluded 0 metric(s)
+++ Combined 1 metric(s) to 1 chart(s)
+ Applying default templates, excluding previously used metrics
++ Applying template 'default-host'
+++ Fetched 2 metric(s) from 'https://grafana.example.com:8542/metrics/expand?query=icinga2.wd-de-hub-1_example_com.host.hostalive.perfdata.%2A.value'
+++ Excluded 2 metric(s)
+++ Combined 0 metric(s) to 0 chart(s)
++ Not applying template 'default-service'

**Comment by nilmerg** [comment] 2022-04-13 09:51
> the default template is used

Oh ah, tested now with the `hostalive` template myself. Works also fine. Got the same debug output as well.

Is there maybe something in the browser console? The graphs are side-loaded also, maybe graphite responds with an error?

**Comment by rweigle** [comment] 2022-04-13 10:03
We are as well using Debian Bullseye and see the same error after the update to 1.2.
We do use the graphite-apu package provided by Debian and the errors we can see are:

Gunicorn Log (hostname has been anonymized):
Message: '{"event": "Exception on /render [GET]", "exception": "Traceback (most recent call last):\\n  File \\>
Apr 13 11:51:05 monitoring gunicorn3[3311378]: Arguments: ()
Apr 13 11:51:05 monitoring gunicorn3[3311378]: {"finder": "whisper", "start": 1649839865, "end": 1649843465, "pattern": "XXXX.host.hosta>
Apr 13 11:51:05 monitoring gunicorn3[3311378]: {"finder": "whisper", "start": 1649839865, "end": 1649843465, "pattern": "XXX.host.hosta>
Apr 13 11:51:05 monitoring gunicorn3[3311378]: {"reader": "whisper", "path": "/var/lib/graphite/whisper/icinga2/XXX/host/hostalive/perfdata/rta>
Apr 13 11:51:05 monitoring gunicorn3[3311378]: {"reader": "whisper", "path": "/var/lib/graphite/whisper/icinga2/XXX/host/hostalive/perfdata/rta>
Apr 13 11:51:05 monitoring gunicorn3[3311378]: --- Logging error ---
Apr 13 11:51:05 monitoring gunicorn3[3311378]: Traceback (most recent call last):
Apr 13 11:51:05 monitoring gunicorn3[3311378]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
Apr 13 11:51:05 monitoring gunicorn3[3311378]:     response = self.full_dispatch_request()
Apr 13 11:51:05 monitoring gunicorn3[3311378]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
Apr 13 11:51:05 monitoring gunicorn3[3311378]:     rv = self.handle_user_exception(e)
Apr 13 11:51:05 monitoring gunicorn3[3311378]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
Apr 13 11:51:05 monitoring gunicorn3[3311378]:     reraise(exc_type, exc_value, tb)
Apr 13 11:51:05 monitoring gunicorn3[3311378]:   File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
Apr 13 11:51:05 monitoring gunicorn3[3311378]:     raise value
Apr 13 11:51:05 monitoring gunicorn3[3311378]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
Apr 13 11:51:05 monitoring gunicorn3[3311378]:     rv = self.dispatch_request()
Apr 13 11:51:05 monitoring gunicorn3[3311378]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
Apr 13 11:51:05 monitoring gunicorn3[3311378]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 13 11:51:05 monitoring gunicorn3[3311378]:   File "/usr/lib/python3/dist-packages/graphite_api/app.py", line 455, in render
Apr 13 11:51:05 monitoring gunicorn3[3311378]:     image = doImageRender(request_options['graphClass'], graph_options)
Apr 13 11:51:05 monitoring gunicorn3[3311378]:   File "/usr/lib/python3/dist-packages/graphite_api/app.py", line 591, in doImageRender
Apr 13 11:51:05 monitoring gunicorn3[3311378]:     img = graphClass(**graphOptions)
Apr 13 11:51:05 monitoring gunicorn3[3311378]:   File "/usr/lib/python3/dist-packages/graphite_api/render/glyph.py", line 383, in __init__
Apr 13 11:51:05 monitoring gunicorn3[3311378]:     self.drawGraph(**params)
Apr 13 11:51:05 monitoring gunicorn3[3311378]:   File "/usr/lib/python3/dist-packages/graphite_api/render/glyph.py", line 841, in drawGraph
Apr 13 11:51:05 monitoring gunicorn3[3311378]:     self.setColor(self.foregroundColor)
Apr 13 11:51:05 monitoring gunicorn3[3311378]:   File "/usr/lib/python3/dist-packages/graphite_api/render/glyph.py", line 410, in setColor
Apr 13 11:51:05 monitoring gunicorn3[3311378]:     raise ValueError("Must specify an RGB 3-tuple, an html color "
Apr 13 11:51:05 monitoring gunicorn3[3311378]: ValueError: Must specify an RGB 3-tuple, an html color string, or a known color alias!

And the icingaweb2.log:
2022-04-13T11:51:05+02:00 - ERROR - RuntimeException in /usr/share/icingaweb2/modules/graphite/library/vendor/iplx/Http/Client.php:173 with message: The requested URL returned error: 500 INTERNAL SERVER ERROR
#0 /usr/share/icingaweb2/modules/graphite/library/vendor/iplx/Http/Client.php(195): iplx\Http\Client->executeHandle()
#1 /usr/share/icingaweb2/modules/graphite/library/Graphite/Graphing/GraphiteWebClient.php(83): iplx\Http\Client->send()
#2 /usr/share/icingaweb2/modules/graphite/library/Graphite/Web/Widget/GraphImage.php(117): Icinga\Module\Graphite\Graphing\GraphiteWebClient->request()
#3 /usr/share/icingaweb2/modules/graphite/library/Graphite/Graphing/Chart.php(105): Icinga\Module\Graphite\Web\Widget\GraphImage->render()
#4 /usr/share/icingaweb2/modules/graphite/application/controllers/GraphController.php(217): Icinga\Module\Graphite\Graphing\Chart->serveImage()
#5 /usr/share/icingaweb2/modules/graphite/application/controllers/GraphController.php(85): Icinga\Module\Graphite\Controllers\GraphController->supplyImage()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Graphite\Controllers\GraphController->hostAction()
#7 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#9 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#10 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#11 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#12 {main}

**Comment by nilmerg** [comment] 2022-04-13 10:17
> Must specify an RGB 3-tuple, an html color string, or a known color alias!

I had this error during development only. The color codes sent to graphite are derived from the theme that is active in Icinga Web 2. Does this happen with all themes or just a specific one? If it's a single theme only, can you show me this? Please also tell me which browser and which version of it you're using.

You could also add this to the theme for a moment to see if it helps:

```
@graphite-graph-bg-color: rgb(245, 249, 250);
@graphite-graph-fg-color: rgb(83, 83, 83);
@graphite-graph-major-grid-color: rgb(208, 211, 218);
@graphite-graph-minor-grid-color: rgb(245, 249, 250);
```

**Comment by rweigle** [comment] 2022-04-13 10:42
Thanks for the fast response.

> > Must specify an RGB 3-tuple, an html color string, or a known color alias!
> 
> I had this error during development only. The color codes sent to graphite are derived from the theme that is active in Icinga Web 2. Does this happen with all themes or just a specific one? If it's a single theme only, can you show me this? Please also tell me which browser and which version of it you're using.

This happens with the Icinga Default theme in all three "Theme Modes".
It is broken in Firefox, Chrome, and Safari (all three on a Mac) so i doubt that this is a browser issue

> 
> You could also add this to the theme for a moment to see if it helps:
> 
> ```
> @graphite-graph-bg-color: rgb(245, 249, 250);
> @graphite-graph-fg-color: rgb(83, 83, 83);
> @graphite-graph-major-grid-color: rgb(208, 211, 218);
> @graphite-graph-minor-grid-color: rgb(245, 249, 250);
> ```
Where exactly to I add this? I have not modified any graphite or icingaweb themes before ;-).

**Comment by nilmerg** [comment] 2022-04-13 11:15
> Where exactly to I add this? I have not modified any graphite or icingaweb themes before ;-).

Well, if it happens with the default theme, this won't change anything. But anyway: Create a file inside Icinga Web 2's public directory (usually /usr/share/icingaweb2/public) at `css/themes/test.less` and insert the lines there. Then choose this theme in your preferences. The mode selection will be disabled, this is expected.

> It is broken in Firefox, Chrome, and Safari (all three on a Mac) so i doubt that this is a browser issue

Maybe not, but it's clearly in your environment only. It works for me fine in Chromium, Chrome and Firefox. Some of my colleagues also have Macs (which I don't) and they never had this issue.

And if the theme is the default one (mode is irrelevant) and Icinga Web 2 is at least v2.9, then there is no technical reason I'm aware of why this should be the cause of this issue.

The actual URL used to access graphite might provide some details still. This is not included in the logs you've shown above.

**Comment by lbetz** [comment] 2022-04-13 11:24
Didn't change anything for me. And all my graphs empty, not only hostalive.

**Comment by rweigle** [comment] 2022-04-13 11:29
> > Where exactly to I add this? I have not modified any graphite or icingaweb themes before ;-).
> 
> Well, if it happens with the default theme, this won't change anything. But anyway: Create a file inside Icinga Web 2's public directory (usually /usr/share/icingaweb2/public) at `css/themes/test.less` and insert the lines there. Then choose this theme in your preferences. The mode selection will be disabled, this is expected.
 I have tested it but it still doesn't work (as expected).

> 
> > It is broken in Firefox, Chrome, and Safari (all three on a Mac) so i doubt that this is a browser issue
> 
> Maybe not, but it's clearly in your environment only. It works for me fine in Chromium, Chrome and Firefox. Some of my colleagues also have Macs (which I don't) and they never had this issue.

A colleague is using Firefox on Linux and has the same issues, so I'm pretty sure that it has nothing to do with the browser enviroment.

> 
> And if the theme is the default one (mode is irrelevant) and Icinga Web 2 is at least v2.9, then there is no technical reason I'm aware of why this should be the cause of this issue.

We are using icingawe2 2.10.1-1.bullseye from packages.icinga.com
 
> 
> The actual URL used to access graphite might provide some details still. This is not included in the logs you've shown above.
The URL is: 
http://127.0.0.1:8542
This has worked before.
Maybe the problem is that we are using the Debian package graphite-api (1.1.3-7.bullseye) and not graphite-web as it is not available on bullseye.

**Comment by nilmerg** [comment] 2022-04-13 11:32
That's only the hostname and port. I'm more interested in the url parameters :grinning:

**Comment by lbetz** [comment] 2022-04-13 11:32
On browser console I got an internal server error.

**Comment by lbetz** [comment] 2022-04-13 11:33
https://10.20.160.121/icingaweb2/graphite/graph/host?host.name=wd-de-hub-2..example.com&host.check_command=hostalive&template=hostalive-rta&start=-28800&end=&width=967&height=220&legend=1&bgcolor=282e39&fgcolor=ffffff&majorGridLineColor=5c5c5c&minorGridLineColor=282e39&r=1649849284465

**Comment by nilmerg** [comment] 2022-04-13 12:53
I don't know, I'm not a sys-admin :joy: Nah, seriously now, @lbetz sent me the access log already where it's obvious that the url parameters are correct. At least in the expected way. My current guess is that it's the backend which doesn't like what it's fed with or that what it is fed with is based on a newer version of graphite-web. The module sends those color parameters according to [this documentation](https://graphite.readthedocs.io/en/latest/render_api.html#bgcolor). But that didn't change even when going back to [v0.9.x](https://graphite.readthedocs.io/en/0.9.x/render_api.html), so there's maybe something else wrong with the backend or the communication with it.

**Comment by rweigle** [comment] 2022-04-19 11:39
We have investigated the issue a little bit further:
Currently an URL created by the module look like this:
﻿﻿﻿https://host.xxx.de/graphite/graph/host?host.name=host.xxx.de&host.check_command=hostalive&template=hostalive-rta&start=-3600&end=&width=1692&height=220&legend=1&bgcolor=f5f9fa&fgcolor=535353&majorGridLineColor=d0d3da&minorGridLineColor=f5f9fa&r=1650358468224

This results in an internal server error. And a python error (reported by guincorn): 
   File "/usr/lib/python3/dist-packages/graphite_api/render/glyph.py", line 410, in setColor 
   raise ValueError("Must specify an RGB 3-tuple, an html color " 
   ValueError: Must specify an RGB 3-tuple, an html color string, or a known color alias!

If we replace the RGB 3-tuple for fgcolor with a color name fgcolor=black we can the see the graph and everything works as expected.
Full working URL:
https://host.xxx.de/graphite/graph/host?host.name=host.xxx.de&host.check_command=hostalive&template=hostalive-rta&start=-3600&end=&width=1692&height=220&legend=1&bgcolor=f5f9fa&fgcolor=black&majorGridLineColor=d0d3da&minorGridLineColor=f5f9fa&r=1650358468224

Maybe an error in the rgbToHex function in module.js???

**Comment by rweigle** [comment] 2022-04-19 11:47
To be more specific all hex-color-codes including letters work, but if  hex color code only includes numbers (e.g. 000000 for black) it breaks. Maybe as it is interpreted as an RGB triplet?

**Comment by nilmerg** [comment] 2022-04-19 12:06
> but if hex color code only includes numbers (e.g. 000000 for black) it breaks.

Yeah, that's the important bit. Based on this I've found [a similar issue](https://answers.launchpad.net/graphite/+question/220017) which has been [fixed in 2016](https://github.com/graphite-project/graphite-web/pull/1596).

You should upgrade to a newer version of the graphite-api port I guess. Or switch over to graphite-web if there's none. Since this isn't an issue in the module, I close here.

**Comment by nilmerg** [comment] 2022-04-19 12:06
Oh, and many thanks for the investigation :P

**Closed by nilmerg** 2022-04-19 12:06 UTC
Labels: needs-feedback

**Comment by rweigle** [comment] 2022-04-19 12:16
> > but if hex color code only includes numbers (e.g. 000000 for black) it breaks.
> 
> Yeah, that's the important bit. Based on this I've found [a similar issue](https://answers.launchpad.net/graphite/+question/220017) which has been [fixed in 2016](https://github.com/graphite-project/graphite-web/pull/1596).
> 
> You should upgrade to a newer version of the graphite-api port I guess. Or switch over to graphite-web if there's none. Since this isn't an issue in the module, I close here.

As the Debian package we are using is already the "newest" version of graphite-api (1.1.3 release in 2016) we probably have to switch to graphite-web, which is a bit unfortunate as it is not in Debian bullseye and we have to install it manually.

**Comment by lbetz** [comment] 2022-04-19 12:22
Why the last release v1.1.0 works fine and the new one breaks it?

**Comment by lbetz** [comment] 2022-04-19 12:27
So you mean it ran stable before because we happened to use the hex codes with not just numbers?

**Comment by rweigle** [comment] 2022-04-20 06:58
The fix that was used for graphite web works for graphite-api as well. As we are using a package packed by @lbetz it would be very nice if it would be fixed in the package.

**Comment by lbetz** [comment] 2022-04-20 08:47
@rweigle ok, it only works with the high contrast theme, not with icinga default.

**Comment by alexbugl** [comment] 2022-04-20 08:52
> @rweigle Gladly, do you have a patch? [...] Since it seems to work for you ...

Here you are:
```diff
diff -u /usr/lib/python3/dist-packages/graphite_api/render/glyph.py.orig /usr/lib/python3/dist-packages/graphite_api/render/glyph.py
--- /usr/lib/python3/dist-packages/graphite_api/render/glyph.py.orig 2022-04-19 15:56:23.518689295 +0200
+++ /usr/lib/python3/dist-packages/graphite_api/render/glyph.py 2022-04-19 16:07:07.621895732 +0200
@@ -406,6 +406,10 @@
                        int(s[4:6], base=16))
             if len(s) == 8 and not forceAlpha:
                 alpha = int(s[6:8], base=16) / 255.0
+        elif isinstance(value, int) and len(str(value)) == 6:
+            s = str(value)
+            r, g, b = (int(s[0:2], base=16), int(s[2:4], base=16),
+                       int(s[4:6], base=16))
         else:
             raise ValueError("Must specify an RGB 3-tuple, an html color "
                              "string, or a known color alias!")
```

**Comment by alexbugl** [comment] 2022-04-20 09:30
> Still doesn't work with any theme other than high contrast.

We see the same problem with the "dark" theme here ...

There are some other colors used -- one seems (in our case) to be:
`minorGridLineColor=282e39`

And this one contains the hex number `e` -- the Python code sees this as a float with exponent:
`2.82e+41, <class \'float\'>`

Currently no good idea how to address that ... :-(

**Comment by lbetz** [comment] 2022-04-20 09:50
But apparently it must be solved in graphite-web.

**Comment by alexbugl** [comment] 2022-04-22 12:17
> There are some other colors used -- one seems (in our case) to be: `minorGridLineColor=282e39`
> And this one contains the hex number `e` -- the Python code sees this as a float with exponent: `2.82e+41, <class \'float\'>`

I think I found where the float comes from: In `/usr/lib/python3/dist-packages/graphite_api/app.py` in `render()` every URL parameter is going through this code:
```python
    for opt in graph_class.customizable:
        if opt in RequestParams:
            value = RequestParams[opt]
            try:
                value = int(value)
            except ValueError:
                try:
                    value = float(value)
                except ValueError:
                    if value.lower() in ('true', 'false'):
                        value = value.lower() == 'true'
                    elif value.lower() == 'default' or not value:
                        continue
            graph_options[opt] = value
```
So if it is not possible to cast `value` to type _int_, it will be cast to _float_. And that succeeds for RGB color `282e39` not as expected ...

I do not see if it is possible to change that code, as one needs to make sure that for _every_ URL parameter some new code really works and has no negative effects ...
Probably it would be easier to modify the URL creation in Icinga -- to set the values for RGB colors to `#282e39 `, as this would be a _string_ which `setColor()` should be able to handle ...

**Comment by lbetz** [comment] 2022-05-03 12:27
@rweigle @alexbugl patch:
--- a/graphite_api/app.py       2022-05-03 12:18:47.242607238 +0000
+++ b/graphite_api/app.py       2022-05-03 12:20:54.924462536 +0000
@@ -300,16 +300,14 @@
     for opt in graph_class.customizable:
         if opt in RequestParams:
             value = RequestParams[opt]
-            try:
+            if (value.isdigit() or (value.startswith('-') and value[1:].isdigit())) and 'color' not in opt.lower():
                 value = int(value)
-            except ValueError:
-                try:
-                    value = float(value)
-                except ValueError:
-                    if value.lower() in ('true', 'false'):
-                        value = value.lower() == 'true'
-                    elif value.lower() == 'default' or not value:
-                        continue
+            elif '.' in value and (value.replace('.','',1).isdigit() or (value.startswith('-') and value[1:].replace('.','',1).isdigit())):
+                value = float(value)
+            elif value.lower() in ('true','false'):
+                value = value.lower() == 'true'
+            elif value.lower() == 'default' or value == '':
+                continue
             graph_options[opt] = value

     tzinfo = pytz.timezone(app.config['TIME_ZONE'])

**Comment by lbetz** [comment] 2022-05-03 15:14
@rweigle debian packages from packages.netways.de/extras is also patched.

**Comment by rweigle** [comment] 2022-05-04 09:03
We have installed the patched graphite-api package from netways and can confirm that it works. Thanks!
