### ISSUE TITLE
no charts appear in host/service Icingaweb tabs - only from Graphite menu

### ISSUE THREAD

**Issue by naksitrallid** [Icinga/icingaweb2-module-graphite#75] opened 2017-10-30 10:03 UTC
i can see no charts or even Graphite element under Problem handling in Host/Service tabs, yet i know for sure charts are working fine because i can see them utilizing Hosts/Services filters from Graphite main menu element

## Current Behavior
i can see no errors in Apache error.log

## Possible Solution
would like to hear it from you

## Steps to Reproduce (for bugs)
ask any questions, i'd be happy to provide all details

## Your Environment
* Module version (System - About): 0.0.0 (Git commit: 1f0fb9d760bea66ad1b7d70ca33fb50a55e49f05)
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): r2.7.1-1
* Operating System and version: Debian 9.2 (Stretch)
* Webserver, PHP versions:  Apache/2.4.25, PHP 7.0.19-1

**Comment by Kareemabdallah** [comment] 2017-11-06 17:08
I have exact the same issue, even though I can see the values and arguments on icinga's overview -> Services section, there is no graph shown, as well as the Graphite module's section on icinga, no graphs provided!

My environment app's versions are all the same as the thread.

**Comment by Al2Klimov** [comment] 2017-11-07 17:03
Closing this as an effective duplicate of https://github.com/Icinga/icingaweb2-module-graphite/issues/74#issuecomment-342550162.

**Closed by Al2Klimov** 2017-11-07 17:03 UTC
