### ISSUE TITLE
SVG returns wrong dates below graph

### ISSUE THREAD

**Issue by pogii123** [Icinga/icingaweb2-module-graphite#111] opened 2017-12-20 13:24 UTC
The rendered SVG returns the wrong dates. The picture shows a two hour range.

![image](https://user-images.githubusercontent.com/14888191/34209024-d3e46942-e590-11e7-9cb3-a383d895e61f.png)

## Your Environment
* Module Version: 0.9.0
* Icinga Web 2 version and modules (System - About): 2.5.0
* Icinga 2 version (`icinga2 --version`): 2.8
* Operating System and version: Rhel 7.4
* Webserver, PHP versions: php 7.1, apache 2.4.x

**Comment by Al2Klimov** [comment] 2018-01-10 17:33
Hello @pogii123 and thank you for reporting!

Please could you tell what is "wrong" w/ those dates for your POV?
IMO 14:00 - 12:00 = 2h

Best,
AK

**Comment by bobapple** [comment] 2018-01-19 12:06
@pogii123 I'm not able to reproduce this, which version of Graphite Web are you using?

Are you using the current master or the tagged 0.9.0 version of this module?

**Comment by pogii123** [comment] 2018-01-30 13:59
Hi @bobapple,

I'm using the tagged 0.9.0 version.

When you tried to reproduce it, did you choose the `2 hour` range? 

With the `1 hour` range, I can see the graph for every quarter of an hour. So everything is working fine.

I apologize for answering now..

Regards,
pogii123

**Comment by Al2Klimov** [comment] 2018-01-31 08:56
Hello @pogii123,

As long as there's no v1.0 I recommend you to use the master as I've fixed some critical bugs since v0.9.

Anyway:

> Please could you tell what is "wrong" w/ those dates for your POV?
> IMO 14:00 - 12:00 = 2h

Best,
AK

**Comment by pogii123** [comment] 2018-01-31 09:17
Hi @Al2Klimov,
the time range is not wrong. But take a look at the times that are stated.

You can't comprehend what time is it exactly. You only see the full hour, not the quarters.

For me its very confusing to determine the time.

Regards,
pogii123

**Comment by bobapple** [comment] 2018-02-07 13:25
@pogii123 I tested this with all quick time ranges that available and I'm not able to reproduce it. Could it be that it's a Graphite issue?

**Comment by pogii123** [comment] 2018-06-08 09:09
Hi @bobapple,

since the new module-graphite version, the problem is no longer existent

**Comment by Al2Klimov** [comment] 2018-06-08 09:11
@pogii123 Which "new version"? Or better: which git commit?

**Comment by pogii123** [comment] 2018-06-08 09:48
@Al2Klimov We updated to version 1.0.1. I don't know, which commit did that.

**Comment by Al2Klimov** [comment] 2018-06-08 11:05
@bobapple IMO we can close this, shall we?

**Closed** 2018-06-08 11:47 UTC
Labels: needs-feedback, stalled
